---
version: '3.8'
services:

  mllp-forwarder:
    container_name: mllp-forwarder
    image: mgarde/mllp-forwarder
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      QUARKUS_LOG_LEVEL: INFO
      LOCAL_MLLP_HOSTNAME: localhost
      LOCAL_MLLP_PORT: 2575
      LOCAL_HTTP_HOSTNAME: localhost
      LOCAL_HTTP_PORT: 2576
      QUARKUS_SWAGGER_UI_ALWAYS_INCLUDE: true
    ports:
      - "8080:8080"
      - "2575:2575"
      - "2576:2576"
    extra_hosts:
      - "host.docker.internal:host-gateway"
